version: '3'
services:
  mongo:
    image: 'mongo:6'
    environment:
      MONGO_INITDB_DATABASE: conferences
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
      TZ: Europe/Paris
    ports:
      - '3702:27017'
  mongo-admin:
    image: 'mongo-express'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: qwerty
    depends_on:
      - mongo
    ports:
      - '3703:8081'
    restart: always
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"